Add use-last parameter
tingerrr/hydra pull request #19
Opened 2024-06-29 07:41 UTC by freundTech

Closes #13.
This allows hydra to alternatively display the last instead of the first candidate on a page, mimicking the behavior of LaTeX.

2024-06-29 07:46 UTC, freundTech commented on src/core.typ
> +    let next-ancestors = query(selector(ctx.ancestors.target).after(ctx.anchor-loc))
I changed some of the variable names to improve readability and code-flow. Previously the same variable was used for multiple things, which would have required me to change code flow (because I needed access to variables that were already overwritten)

2024-06-29 07:46 UTC, freundTech commented on src/core.typ
> +  next-targets = next-targets.filter(x => x.location().page() == ctx.anchor-loc.page())
This could be put behind a `if ctx.use-last` guard, but I don't think it's necessary. I can't think of any case where you would want hydra to display a heading that is defined on the *next* page.

2024-06-29 07:46 UTC, freundTech commented on src/core.typ
> +    primary: (prev: prev, next: next, last: last),
I thought about just setting `next: last` if `ctx.use-last` is set, but that breaks the redundancy checking. That still requires `next`, even if `use-last` is set.

2024-06-29 07:46 UTC, freundTech commented on src/core.typ
> +    }
I would have liked to simplify this a bit, but I couldn't figure out a simpler solution.

2024-06-29 07:55 UTC, freundTech commented
Noticed that my PR was already outdated when I created it. Just rebased and force-pushed.

2024-06-29 16:51 UTC, tingerrr requested changes
A few tiny changes and it's good to go! Surprisingly simple solution as it turns out.

2024-06-29 16:51 UTC, tingerrr commented on src/core.typ
> +    primary: (prev: prev, next: next, last: last),
Yeah, that makes sense. This must still be documented in the manual in the custom types section.

2024-06-29 16:51 UTC, tingerrr commented on src/core.typ
> +    }
This one's tricky, it was already a little hard to follow before. I think you can invert a few conditions and use early `return` to make this easier to read.

2024-06-29 16:51 UTC, tingerrr commented on src/lib.typ
> +//    Defaults to false.
A little slip up here, I assume.

2024-06-30 15:03 UTC, freundTech commented on src/core.typ
> +    primary: (prev: prev, next: next, last: last),
Done

2024-06-30 15:14 UTC, freundTech commented
I reworked it a bit.
`get-candidates` no longer considers `ctx.use-last`, but always returns correct `prev`, `next` and `last`, while `execute` chooses which of these to display.

`execute` is now significantly easier.

2024-06-30 20:12 UTC, tingerrr approved these changes
LGTM, Thanks!

2024-06-30 20:24 UTC, merged

2024-07-02 22:12 UTC, freundTech commented
Are you planning to make a release for this or are you waiting for more changes?
I would like to stop vendoring hydra into my thesis :wink:

2024-07-03 07:20 UTC, tingerrr commented
I'll prepare some releases today, since I have to fix some stuff on subpar. A shame I couldn't get the mantys PR ready in time, but it is what it is.